# Generated by Django 4.2.26 on 2025-12-09 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('affirmed', 'Affirmed'), ('reversed', 'Reversed'), ('remanded', 'Remanded'), ('dismissed', 'Dismissed'), ('settled', 'Settled'), ('vacated', 'Vacated'), ('other', 'Other')], max_length=50)),
                ('decision_days', models.IntegerField(blank=True, null=True)),
                ('disposition', models.TextField(blank=True)),
                ('precedential_status', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'case_outcomes',
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('short_name', models.CharField(blank=True, max_length=200)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('court_type', models.CharField(blank=True, max_length=100)),
                ('citation_string', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'courts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docket_id', models.IntegerField(db_index=True, unique=True)),
                ('case_name', models.CharField(max_length=1000)),
                ('case_name_short', models.CharField(blank=True, max_length=500)),
                ('case_name_full', models.CharField(blank=True, max_length=2000)),
                ('docket_number', models.CharField(blank=True, db_index=True, max_length=200)),
                ('date_filed', models.DateField(blank=True, db_index=True, null=True)),
                ('date_terminated', models.DateField(blank=True, null=True)),
                ('date_last_filing', models.DateField(blank=True, null=True)),
                ('nature_of_suit', models.CharField(blank=True, db_index=True, max_length=500)),
                ('cause', models.CharField(blank=True, max_length=500)),
                ('jury_demand', models.CharField(blank=True, max_length=200)),
                ('jurisdiction_type', models.CharField(blank=True, max_length=200)),
                ('parties', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='court_listener', max_length=100)),
                ('pacer_case_id', models.CharField(blank=True, max_length=200)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dockets',
                'ordering': ['-date_filed'],
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_id', models.IntegerField(db_index=True, unique=True)),
                ('name_first', models.CharField(blank=True, max_length=200)),
                ('name_middle', models.CharField(blank=True, max_length=200)),
                ('name_last', models.CharField(blank=True, max_length=200)),
                ('name_suffix', models.CharField(blank=True, max_length=50)),
                ('full_name', models.CharField(db_index=True, max_length=500)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('date_death', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('race', models.CharField(blank=True, max_length=100)),
                ('dob_city', models.CharField(blank=True, max_length=200)),
                ('dob_state', models.CharField(blank=True, max_length=100)),
                ('biography', models.TextField(blank=True)),
                ('education', models.JSONField(blank=True, default=list)),
                ('positions', models.JSONField(blank=True, default=list)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'judges',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion_id', models.IntegerField(db_index=True, unique=True)),
                ('type', models.CharField(choices=[('010combined', 'Combined Opinion'), ('020lead', 'Lead Opinion'), ('030concurrence', 'Concurrence'), ('040dissent', 'Dissent'), ('050addendum', 'Addendum')], default='010combined', max_length=50)),
                ('plain_text', models.TextField(blank=True)),
                ('html', models.TextField(blank=True)),
                ('html_lawbox', models.TextField(blank=True)),
                ('html_columbia', models.TextField(blank=True)),
                ('html_anon_2020', models.TextField(blank=True)),
                ('html_with_citations', models.TextField(blank=True)),
                ('date_filed', models.DateField(blank=True, db_index=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('download_url', models.URLField(blank=True, max_length=500)),
                ('local_path', models.FileField(blank=True, upload_to='opinions/')),
                ('extracted_citations', models.JSONField(blank=True, default=list)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_opinions', to='court_data.judge')),
            ],
            options={
                'db_table': 'opinions',
                'ordering': ['-date_filed'],
            },
        ),
        migrations.CreateModel(
            name='Statute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statute_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('section', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
                ('jurisdiction', models.CharField(max_length=100)),
                ('jurisdiction_type', models.CharField(max_length=50)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('repeal_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_opinions', models.ManyToManyField(blank=True, related_name='cited_statutes', to='court_data.opinion')),
            ],
            options={
                'db_table': 'statutes',
                'ordering': ['title', 'section'],
            },
        ),
        migrations.CreateModel(
            name='OpinionsCited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField(default=1)),
                ('citation_text', models.TextField(blank=True)),
                ('influence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cited_opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cited_by', to='court_data.opinion')),
                ('citing_opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cites_to', to='court_data.opinion')),
            ],
            options={
                'db_table': 'opinions_cited',
            },
        ),
        migrations.CreateModel(
            name='OpinionCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(db_index=True, unique=True)),
                ('case_name', models.CharField(max_length=1000)),
                ('case_name_short', models.CharField(blank=True, max_length=500)),
                ('case_name_full', models.CharField(blank=True, max_length=2000)),
                ('date_filed', models.DateField(blank=True, db_index=True, null=True)),
                ('citation_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('docket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='court_data.docket')),
                ('non_participating_judges', models.ManyToManyField(blank=True, related_name='non_participating_cases', to='court_data.judge')),
                ('panel', models.ManyToManyField(blank=True, related_name='panel_memberships', to='court_data.judge')),
            ],
            options={
                'db_table': 'opinion_clusters',
                'ordering': ['-date_filed'],
            },
        ),
        migrations.AddField(
            model_name='opinion',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_opinions', to='court_data.opinioncluster'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='joined_by',
            field=models.ManyToManyField(blank=True, related_name='joined_opinions', to='court_data.judge'),
        ),
        migrations.CreateModel(
            name='JudgeDocketRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('author', 'Author'), ('joined', 'Joined'), ('dissent', 'Dissent'), ('concurrence', 'Concurrence'), ('presiding', 'Presiding Judge'), ('panel', 'Panel Member')], max_length=50)),
                ('outcome', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('docket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_relations', to='court_data.docket')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docket_relations', to='court_data.judge')),
            ],
            options={
                'db_table': 'judge_docket_relations',
            },
        ),
        migrations.AddIndex(
            model_name='judge',
            index=models.Index(fields=['full_name'], name='judges_full_na_a5c7be_idx'),
        ),
        migrations.AddField(
            model_name='docket',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dockets', to='court_data.court'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['jurisdiction'], name='courts_jurisdi_8dd808_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['position'], name='courts_positio_fb9555_idx'),
        ),
        migrations.AddField(
            model_name='caseoutcome',
            name='docket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='court_data.docket'),
        ),
        migrations.AddIndex(
            model_name='statute',
            index=models.Index(fields=['jurisdiction'], name='statutes_jurisdi_ce4d84_idx'),
        ),
        migrations.AddIndex(
            model_name='opinionscited',
            index=models.Index(fields=['citing_opinion'], name='opinions_ci_citing__2c7c29_idx'),
        ),
        migrations.AddIndex(
            model_name='opinionscited',
            index=models.Index(fields=['cited_opinion'], name='opinions_ci_cited_o_0e985c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opinionscited',
            unique_together={('citing_opinion', 'cited_opinion')},
        ),
        migrations.AddIndex(
            model_name='opinioncluster',
            index=models.Index(fields=['-citation_count'], name='opinion_clu_citatio_7adcfc_idx'),
        ),
        migrations.AddIndex(
            model_name='opinion',
            index=models.Index(fields=['author'], name='opinions_author__68dc8d_idx'),
        ),
        migrations.AddIndex(
            model_name='judgedocketrelation',
            index=models.Index(fields=['judge', 'outcome'], name='judge_docke_judge_i_b90835_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='judgedocketrelation',
            unique_together={('judge', 'docket', 'role')},
        ),
        migrations.AddIndex(
            model_name='docket',
            index=models.Index(fields=['-date_filed'], name='dockets_date_fi_a9ccc8_idx'),
        ),
        migrations.AddIndex(
            model_name='docket',
            index=models.Index(fields=['nature_of_suit'], name='dockets_nature__03b25a_idx'),
        ),
        migrations.AddIndex(
            model_name='caseoutcome',
            index=models.Index(fields=['outcome_type'], name='case_outcom_outcome_f288bf_idx'),
        ),
    ]
