# Generated by Django 4.2.26 on 2025-11-25 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('court_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(db_index=True, unique=True)),
                ('case_name', models.CharField(max_length=1000)),
                ('case_name_short', models.CharField(blank=True, max_length=500)),
                ('case_name_full', models.CharField(blank=True, max_length=2000)),
                ('date_filed', models.DateField(blank=True, db_index=True, null=True)),
                ('citation_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'opinion_clusters',
                'ordering': ['-date_filed'],
            },
        ),
        migrations.CreateModel(
            name='OpinionsCited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField(default=1)),
                ('citation_text', models.TextField(blank=True)),
                ('influence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'opinions_cited',
            },
        ),
        migrations.AlterUniqueTogether(
            name='citation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='citation',
            name='source_opinion',
        ),
        migrations.RemoveField(
            model_name='citation',
            name='target_opinion',
        ),
        migrations.RemoveIndex(
            model_name='caseoutcome',
            name='case_outcom_decisio_093905_idx',
        ),
        migrations.RemoveIndex(
            model_name='court',
            name='courts_court_t_672e09_idx',
        ),
        migrations.RemoveIndex(
            model_name='docket',
            name='dockets_case_na_5c6963_idx',
        ),
        migrations.RemoveIndex(
            model_name='judge',
            name='judges_name_la_2c79bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='judgedocketrelation',
            name='judge_docke_docket__08d989_idx',
        ),
        migrations.RemoveIndex(
            model_name='opinion',
            name='opinions_date_fi_039166_idx',
        ),
        migrations.RemoveIndex(
            model_name='opinion',
            name='opinions_type_b0e015_idx',
        ),
        migrations.RemoveIndex(
            model_name='statute',
            name='statutes_is_acti_642650_idx',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='docket',
        ),
        migrations.AddField(
            model_name='court',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opinion',
            name='html_with_citations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='caseoutcome',
            name='decision_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docket',
            name='nature_of_suit',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='judge',
            name='full_name',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='judgedocketrelation',
            name='outcome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='statute',
            name='jurisdiction',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='statute',
            name='jurisdiction_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['position'], name='courts_positio_fb9555_idx'),
        ),
        migrations.AddIndex(
            model_name='opinion',
            index=models.Index(fields=['author'], name='opinions_author__68dc8d_idx'),
        ),
        migrations.DeleteModel(
            name='Citation',
        ),
        migrations.AddField(
            model_name='opinionscited',
            name='cited_opinion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cited_by', to='court_data.opinion'),
        ),
        migrations.AddField(
            model_name='opinionscited',
            name='citing_opinion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cites_to', to='court_data.opinion'),
        ),
        migrations.AddField(
            model_name='opinioncluster',
            name='docket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='court_data.docket'),
        ),
        migrations.AddField(
            model_name='opinioncluster',
            name='non_participating_judges',
            field=models.ManyToManyField(blank=True, related_name='non_participating_cases', to='court_data.judge'),
        ),
        migrations.AddField(
            model_name='opinioncluster',
            name='panel',
            field=models.ManyToManyField(blank=True, related_name='panel_memberships', to='court_data.judge'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='cluster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_opinions', to='court_data.opinioncluster'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='opinionscited',
            index=models.Index(fields=['citing_opinion'], name='opinions_ci_citing__2c7c29_idx'),
        ),
        migrations.AddIndex(
            model_name='opinionscited',
            index=models.Index(fields=['cited_opinion'], name='opinions_ci_cited_o_0e985c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opinionscited',
            unique_together={('citing_opinion', 'cited_opinion')},
        ),
        migrations.AddIndex(
            model_name='opinioncluster',
            index=models.Index(fields=['-citation_count'], name='opinion_clu_citatio_7adcfc_idx'),
        ),
    ]
