# Generated by Django 4.2.26 on 2025-12-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('court_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docket',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='embedding',
        ),
    ]
