# Generated by Django 4.2.26 on 2025-12-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_data', '0002_remove_docket_embedding_remove_judge_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judge',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statute',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
