# Generated by Django 4.2.26 on 2025-12-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_data', '0002_opinioncluster_opinionscited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='monetary_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='docket',
            name='outcome_status',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
