# Generated by Django 4.2.26 on 2025-12-22 17:06

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('court_data', '0003_docket_embedding_judge_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='judge',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='statute',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
