# Generated by Django 4.2.26 on 2025-12-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_data', '0003_docket_monetary_amount_docket_outcome_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statute',
            name='related_opinions',
        ),
        migrations.AddField(
            model_name='docket',
            name='decision_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docket',
            name='precedential_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='judgedocketrelation',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='CaseOutcome',
        ),
        migrations.DeleteModel(
            name='Statute',
        ),
    ]
