# Generated by Django 4.2.26 on 2025-12-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_data', '0004_remove_statute_related_opinions_docket_decision_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statute_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
                ('jurisdiction', models.CharField(blank=True, max_length=100)),
                ('jurisdiction_type', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_opinions', models.ManyToManyField(blank=True, related_name='cited_statutes', to='court_data.opinion')),
            ],
            options={
                'db_table': 'statutes',
                'indexes': [models.Index(fields=['statute_id'], name='statutes_statute_18a0ad_idx'), models.Index(fields=['title'], name='statutes_title_cd5f05_idx')],
            },
        ),
    ]
