# Generated by Django 4.2.26 on 2025-12-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_data', '0005_statute'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='fjc_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
