# Generated by Django 4.2.26 on 2025-12-24 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('court_data', '0005_conversation_message'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS conversations CASCADE;"),
        migrations.RunSQL("DROP TABLE IF EXISTS messages CASCADE;"),
    ]
